# Naive Bayes Theorem

In [3]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import*
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [27]:
df = pd.read_csv("train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### Convert Categorical into Numerical

In [28]:
objList=['Sex','Embarked']
print (objList)

['Sex', 'Embarked']


In [29]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feat in objList:
    df[feat] = le.fit_transform(df[feat])

df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

### D.V and IDV

In [30]:
df=df.drop(['Name','Ticket','Cabin'],axis=1)
DV = ['Survived','Sex','Pclass','SibSp','Parch','Embarked']
#x will be df.drop([y])
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

### Spliting Train and test datasets, Applying Naive Bayes Theorem

In [31]:
clf = BernoulliNB()

In [65]:
def diag(matrix,s):
    tot =0
    for i in range(0,s):
        tot=tot+ matrix[i][i]
    return tot




for a in DV:
    y=df[a]
    X=df.drop([a,'PassengerId'],axis=1)
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
    y_pred=clf.fit(X_train,y_train).predict(X_test)
    score = accuracy_score(y_test,y_pred,normalize=True)
    matrix= confusion_matrix(y_test,y_pred)
    s=matrix.shape[0]
    correct_records=diag(matrix,s)
    print(a,"-"," Accuracy Score: ",score)
    print("    ","Confusion Matrix: ",matrix)
    print("    ","No. of recorders which are classified correctly are: ",correct_records)
    
    print('\n')

Survived -  Accuracy Score:  0.7715355805243446
     Confusion Matrix:  [[131  26]
 [ 35  75]]
     No. of recorders which are classified correctly are:  206


Sex -  Accuracy Score:  0.7453183520599251
     Confusion Matrix:  [[ 49  49]
 [ 19 150]]
     No. of recorders which are classified correctly are:  199


Pclass -  Accuracy Score:  0.5917602996254682
     Confusion Matrix:  [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]
     No. of recorders which are classified correctly are:  158


SibSp -  Accuracy Score:  0.6891385767790262
     Confusion Matrix:  [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]
     No. of recorders which are classified correctly are:  184


Parch -  Accuracy Score:  0.7153558052434457
     Confusion Matrix:  [[182  16   0   0   0]
 [ 31   9   0   0   0]
 [ 24   3   0   0   0]
 [  1   0   0 

Thus, the most accurate records are classified for " Survived " as the Target variable. So, this data is most suitable for Classifying whether a person Survived or Not.