# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
arr = np.empty((3,3,3))
print(arr)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [2.78145267e-307 1.89144519e-307 3.56022682e-307]
  [3.11522733e-307 7.56599807e-307 8.90104239e-307]]

 [[1.24610383e-306 1.69118108e-306 8.06632139e-308]
  [1.20160711e-306 1.69119330e-306 8.90098127e-307]
  [1.95820216e-306 7.56604561e-307 8.45590539e-307]]

 [[1.11261298e-306 6.23054633e-307 1.42418036e-306]
  [9.34598247e-307 9.79094970e-307 1.78019354e-306]
  [1.69120552e-306 2.56765117e-312 5.24288001e+006]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [9]:
import numpy as np
arr = np.zeros((5,5))
arr[1][0]=1
arr[2][1]=2
arr[3][2]=3
arr[4][3]=4
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
import numpy as np
arr = np.zeros((8,8))
i=0
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [34]:
import numpy as np
a = np.random.rand(5,5)
print("Array: ",a)
norm = np.linalg.norm(a)
norm_arr=a/norm
print("Normalized Array:",norm_arr)

Array:  [[0.29889822 0.48795212 0.76274236 0.98015559 0.71331386]
 [0.47447715 0.14481102 0.64583511 0.25634468 0.73777235]
 [0.25965413 0.52863618 0.19251056 0.65601227 0.04818501]
 [0.36312987 0.89993983 0.9002989  0.41412137 0.63619235]
 [0.81879362 0.53252872 0.58858274 0.74878561 0.26765512]]
Normalized Array: [[0.10116255 0.16514812 0.25815129 0.33173512 0.24142214]
 [0.1605875  0.04901151 0.21858386 0.08676024 0.24970015]
 [0.08788033 0.17891771 0.06515549 0.22202833 0.01630829]
 [0.12290185 0.30458598 0.30470751 0.14016    0.21532025]
 [0.27712192 0.18023514 0.19920671 0.25342761 0.09058828]]


# 5.  How to find common values between two arrays?

In [25]:
arr1 = [1,2,3]
arr2=[2,3,5]
print(np.intersect1d(arr1,arr2))

[2 3]


# 6.How to get the dates of yesterday, today and tomorrow?

In [29]:
import datetime
today=datetime.date.today()
yesterday=today - datetime.timedelta(days=1)
tomorrow = today+datetime.timedelta(days=1)

print(yesterday)
print(today)
print(tomorrow)

2020-07-24
2020-07-25
2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [41]:
a=np.random.rand(2,2)
b=np.random.rand(2,2)
print("a:",a)
print("b:",b)
if (a==b).all():
    print("They are equal")
else:
    print("They are not equal")

a: [[0.31401214 0.17584824]
 [0.85540669 0.60191191]]
b: [[0.01186887 0.16603074]
 [0.51519702 0.56939143]]
They are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [47]:
v=np.random.rand(10)
print(v)
max_no = np.where(v==v.max())
v[max_no]=0
print(v)


[0.8237422  0.85822132 0.4471158  0.57473365 0.63925567 0.42243541
 0.41775157 0.56700411 0.8269108  0.91328795]
[0.8237422  0.85822132 0.4471158  0.57473365 0.63925567 0.42243541
 0.41775157 0.56700411 0.8269108  0.        ]


# 9. How to print all the values of an array?

In [51]:
arr = np.array([[1,2,3],[12,23,45]])
print(arr)

[[ 1  2  3]
 [12 23 45]]


# 10.Subtract the mean of each row of a matrix

In [59]:
mat = np.random.rand(2,3)
print(mat)
new_mat = mat -  mat.mean(axis=1,keepdims=True)
print(new_mat)


[[0.44150776 0.68271297 0.46632265]
 [0.68133967 0.18158555 0.80151453]]
[[-0.08867337  0.15253185 -0.06385848]
 [ 0.12652642 -0.3732277   0.24670128]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [4]:
def repeated(v):
    dup_items = set()
    uniq_items = []
    for x in v:
        if x not in dup_items:
            uniq_items.append(x)
            dup_items.add(x)
    return uniq_items
    
import numpy as np
v=np.array([1,2,5,7,8])
index = np.array([1,1,2,0])
new_index=repeated(index)
for a in new_index:
    v[a]=v[a]+1
print(v)


[2 3 6 7 8]


# 12.How to get the diagonal of a dot product?

In [9]:
a=np.array([[1,2,3],[2,5,4]])
b=np.array([[2,3],[8,5],[9,6]])
c=a.dot(b)
print(np.diagonal(c))

[45 55]


# 13.How to find the most frequent value in an array?

In [42]:
import numpy as np
from scipy import stats

a = np.array([1, 3, 4, 2, 2, 2])

bin = np.bincount(a)
print(bin.argmax())

2


# 14.How to get the n largest values of an array

In [56]:
a = np.array([1, 3, 4, 2, 2,2])
n=3
v=a[np.argsort(a)]
print(v[-n:])
        

[2 3 4]


# 15.How to create a record array from a regular array?

In [62]:
import numpy as np
arra1 = np.array([("VAISHNAVI", 20, 90),
                 ("VARAD", 17, 99),
             ("ANJALI", 48, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='NAME, AGE, MARKS')
print(result)

Original arrays:
[['VAISHNAVI' '20' '90']
 ['VARAD' '17' '99']
 ['ANJALI' '48' '91']]

Record array;
[('VAISHNAVI', '20', '90') ('VARAD', '17', '99') ('ANJALI', '48', '91')]
